GET http://localhost:8080/api/reissue
Accept: application/json
Refresh_Token:

###
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "username": "hyundo12",
  "password": "park123"
}

###
POST http://localhost:8080/api/members/signup
Content-Type: application/json

{
  "username": "hyundo12",
  "password": "park123",
  "email": "ato88@naver.com",
  "passwordConfirm": "park123"
}

###
GET http://localhost:8080/api/boards/list
Accept: application/json

###
GET http://localhost:8080/api/boards/detail/3
Accept: application/json

###
POST http://localhost:8080/api/boards/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZG8xMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjY3OTc1NzF9.Na3YOMXYNcmDZrjGm3UY9F_LRP73ouFqu55vACSQ5Uk

{
  "title": "꿈이야기",
  "content": "오늘 꿈에서도 코딩을했다. 현실과 꿈이 분간이 안되고있다.."
}

###
PUT http://localhost:8080/api/boards/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZG8xMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjY3OTg4MTF9.b4NM4AAWFcOkWDL-MjedimxeWEsYvR2Krc_NM6KONmg


{
  "title": "어 ? 옙흐다",
  "content": "준이에용. ㅎㅎㅎㅎ"
}

###
DELETE http://localhost:8080/api/boards/delete/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZG8xMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjY3Mjg2MzV9.Qxq1vk6wCFef496uSOSBugFzgo6Vr04so9xS9PIzcl8

###
GET http://localhost:8080/api/boards/1/comments
Accept: application/json

###
GET http://localhost:8080/api/boards/comments/3
Accept: application/json

###
POST http://localhost:8080/api/boards/3/comments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZG8xMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjY4MDQxMjR9.G6Vu9KSqO5bSW-kPcUjqyAuk7X5YqyHJeoC3CeRRycs

{
  "comment": "갓성호 갓소희 갓연일 갓성민 하현도 ㄱㄱㄱ"
}

###
PUT http://localhost:8080/api/boards/comments/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZG8xMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjY2OTgxMjJ9.56yJGismSFAyfdlo8TyHymwKFJqkBh-JGcRhmNtkMBw

{
  "comment": "Spring Data JPA Comment update"
}

###
DELETE http://localhost:8080/api/boards/comments/delete/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZG8xMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjY3MTAyNDR9.s42cY1TWKIMPA9az8tgxwf5chzowbq7HYy-zzODhR28


###
POST http://localhost:8080/api/heart/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJheWkxMjM0IiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NjU5NTA3NH0.D25rnufwWs8DdltWvRGOrvlfb6jIYeJMJJ6kMh5tbt0
